# Generated by Django 3.0.6 on 2020-05-25 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMap', '0002_auto_20200525_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodelocation',
            name='geom',
        ),
    ]
