# Generated by Django 3.0.6 on 2020-05-26 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminMap', '0003_remove_nodelocation_geom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NodeLocation',
        ),
    ]
