# Generated by Django 3.0.6 on 2020-05-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeBreakerDataTable',
            fields=[
                ('coffeeID', models.CharField(db_column='coffeeID', max_length=40)),
                ('id', models.CharField(db_column='id', max_length=40, primary_key=True, serialize=False)),
                ('water', models.CharField(db_column='water', max_length=40)),
                ('milk', models.CharField(db_column='milk', max_length=40)),
                ('sugar', models.CharField(db_column='sugar', max_length=40)),
                ('date', models.CharField(db_column='date', max_length=40)),
            ],
        ),
    ]
